site_name: Sensei's Test2
theme:
  name: material

markdown_extensions:
  # Mermaid support - fancy diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
